# config/defaults.py

DEFAULT_BOT_TOKEN = "YOUR_BOT_TOKEN"
DEFAULT_CHAT_ID = "YOUR_CHAT_ID"

DEFAULT_FAILED_ATTEMPT_THRESHOLD = 2
DEFAULT_EVENT_ID = 4625
DEFAULT_CHECK_INTERVAL_SECONDS = 0.1

DEFAULT_DEVICE_INDEX = 0
CURRENT_CONFIG_VERSION = 1
