# config/defaults.py

DEFAULT_BOT_TOKEN = "YOUR_BOT_TOKEN"
DEFAULT_CHAT_ID = "YOUR_CHAT_ID"

DEFAULT_FAILED_ATTEMPT_THRESHOLD = 2
DEFAULT_EVENT_ID = 4625
DEFAULT_CHECK_INTERVAL_SECONDS = 0.1

DEFAULT_DEVICE_INDEX = 0

DEFAULT_FACE_VERIFICATION_ENABLED = False
DEFAULT_FACE_VERIFICATION_THRESHOLD = 0.363

DEFAULT_VAULT_ENABLED = True
DEFAULT_VAULT_TARGET_DIR = r"C:\VigiLoVault"
DEFAULT_VAULT_KEY = ""

DEFAULT_WHATSAPP_ENABLED = False
DEFAULT_WHATSAPP_PHONE_NUMBER_ID = ""
DEFAULT_WHATSAPP_ACCESS_TOKEN = ""
DEFAULT_WHATSAPP_RECIPIENT_PHONE = ""

CURRENT_CONFIG_VERSION = 4
